package.json
src/components/Carousel/Carousel.tsx
src/components/ChatBox/ChatBox.tsx
src/components/Preview/Preview.tsx
yarn.lock

Fixes:
- Credit Card info showing up as autofill in Preview input field
- Carousel rendering black page when tile count is updated from last page

fix: preview name autofill, carousel state on tile count change

---

package.json
src/components/ControlBar/ControlBar.tsx
src/components/Preview/Preview.tsx

- fixes preview screen UI in mweb,webview, safari
- fix spacing in controlbar on safari
- simplify controlbar css

fix: mweb, safari css fixes

---

package.json
yarn.lock

https://100ms.atlassian.net/browse/LIVE-183
https://github.com/100mslive/hms-video-web/pull/105

chore: update sdk for packets on video mute

---

package.json
src/components/ControlBar/ControlBar.tsx
src/components/ParticipantList/ParticipantInList.tsx
src/components/ParticipantList/ParticipantList.tsx
src/components/Preview/Preview.tsx
src/components/Silence/index.tsx
src/components/VideoTile/Controls/Controls.tsx
yarn.lock

- Show loader in preview while joining
- Truncate longer texts in VideoTile and ParticipantList
- increase preview video height for mweb

fix: ui fixes and enhancements

---

package.json
src/components/ChatBox/ChatBox.tsx
src/components/ControlBar/ControlBar.tsx
src/components/FirstPersonDisplay/FirstPersonDisplay.tsx
src/components/Notifications/notification.css
src/components/Preview/Controls/PreviewControls.tsx
src/components/Preview/Preview.tsx
src/components/Preview/index.css
src/components/Settings/Settings.tsx
src/defaultTheme.tsx
src/index.ts
src/utils/index.ts
yarn.lock

- Center align video/mic buttons
- Place notifications above footer when shown bottom left
- Remove view count selector for mobile from settings
- Handle zerowidthspace in Preview name
- Fix firstpersondisplay ui
- Fix preview landscape

fix: alignment issues and bug fixes

---

package.json
yarn.lock

- published to latest : 0.2.57

chore: update sdk, store

---

package.json
src/components/Settings/Settings.tsx
src/storybook/store/StoryBookSDK.ts
yarn.lock

Participant count not working
Call onChange when participant value changes

fix: pariticipant count

---

package.json
src/components/Settings/Settings.tsx

- Newly selected devices selected from dropdown are not properly applied
- Use correct value to update selection

fix: device change from settings

---

package.json
src/components/ParticipantList/ParticipantList.tsx
src/components/ParticipantList/ParticipantProps.ts
yarn.lock

- Added an option for force change

feat: add force change option

---

package.json
src/storybook/store/StoryBookSDK.ts
yarn.lock

chore: update to latest, update sdk and store

---

package.json

chore: update to latest

---

.github/pull_request_template.md
src/components/Settings/TestAudio.tsx
src/components/Video/Video.tsx
src/components/VideoTile/VideoTile.tsx

Merge main to develop

---

package.json
src/hooks/HMSRoomProvider.tsx
src/storybook/store/SetUpFakeStore.ts
yarn.lock

* devtools will now show actions which are changing state

chore: update store for named setstate

---

package.json
src/components/ControlBar/ControlBar.tsx
src/components/Preview/Controls/PreviewControls.tsx
src/components/Preview/Preview.tsx
src/components/Settings/Settings.stories.tsx
src/components/Settings/Settings.tsx
src/components/Video/Video.tsx
yarn.lock

- Video is not detached when out of view
- Detach video when out of view

fix: attach and detach video element properly

---

package.json
yarn.lock

chore: update store and sdk

---

package.json
src/components/ChatBox/ChatBox.tsx
src/components/ChatBox/ChatSelector.tsx
src/components/ContextMenu/ContextMenu.tsx
src/storybook/store/StoryBookSDK.ts
yarn.lock

- You will be send messages to the whole room
- You will be able to send to selective peers or selective roles.

feat: add ui for chat to send private messages

---

package.json
yarn.lock

chore: update post css

---

package.json
yarn.lock

refactor: version updated with latest plugin frame rate handling changes

---

package.json
yarn.lock

chore: Bump latest 0.3.32

---

package.json
src/components/ChatBox/ChatSelector.tsx
yarn.lock

https://100ms.atlassian.net/browse/HMS-3617
- Manually delete every character
- Add a cross to clear all search

fix: add cross icon to clear search in chat 

---

package.json

chore: bump version to 0.3.43

---

package.json
src/components/TwAvatar/Avatar.tsx
src/components/TwAvatar/index.css
yarn.lock

- Fixed size is given to avatar
- Take 1/3 of container as avatar size
- Calculate font size to 1/3 of avatar size

fix: avtar size

---

package.json
src/components/Icons/Icons.tsx
yarn.lock

chore: noise supression button

---

package.json
yarn.lock

chore: update store, bump version

---

package.json
src/components/MessageModal/MessageModal.tsx
yarn.lock

chore: update deps, bump to 0.3.60

---

.github/pull_request_template.md

* remove before/after, only details

chore: change pr template format

---

README.md

docs: add deprecation notice for react components

---

package.json
yarn.lock

* Audio/video playlist featues

chore: update store, bump to latest

---

package.json
src/components/Playlist/VideoPlaylist.tsx

* allow custom trigger icon in VideoPlaylist

fix: video playlist trigger icon

---

src/components/Preview/Preview.tsx

* Fix race condition between preview and leave

fix: preview race condition after leave

---

package.json
src/components/Playlist/PlaylistControls.tsx

* Feat add seek to position in audio/video playlist

feat: add seek to playlist

---

package.json
src/components/Playlist/PlaylistControls.tsx
yarn.lock

* Show volume control, fullscreen for video player on receiver's end

feat: show volume control, fullscreen for playlist

---

package.json
src/components/AudioLevelIndicators/index.tsx
src/components/Video/Video.tsx
src/components/VideoTile/VideoTile.tsx

* Fix excess rerenders of video tile

fix: optimise audio level render

---

package.json
yarn.lock

chore(fixes): update store@0.2.47

---

.github/workflows/npm-publish.yml

build: manual alpha publish

---

package.json
src/components/AudioLevelIndicators/Border.tsx
src/components/AudioLevelIndicators/index.tsx
src/components/AudioLevelIndicators/useAudioLevel.ts

* Update audiolevel with ref instead of state updates
*

fix: update audiolevel with ref

---

package.json
yarn.lock

chore: bump version, update sdk, store

---

package.json
src/components/Playlist/PlaylistControls.tsx
yarn.lock

chore: bump version, update store, sdk

---

package.json
src/components/ContextMenu/ContextMenu.tsx
src/components/MessageModal/MessageModal.tsx
src/components/ParticipantsInView/ParticipantsInView.tsx
src/components/Playlist/AudioPlaylist.tsx
src/components/Playlist/PlaylistControls.tsx
src/components/Playlist/PlaylistItem.tsx
src/components/Playlist/VideoPlayer.tsx
src/components/Playlist/VideoPlaylist.tsx
src/components/Settings/Settings.tsx

- Reduces render time of few components

fix: remove deps for styler

---

package.json
src/components/VideoList/VideoList.stories.tsx
src/components/VideoTile/Controls/Controls.tsx
src/components/VideoTile/VideoTile.stories.tsx
src/components/VideoTile/VideoTile.tsx

fix: video tile menu not visibile

---

package.json
yarn.lock

chore: update store

---

package.json
yarn.lock

chore: update sdk, store and bump version

---

package.json
src/components/ChatBox/ChatBox.tsx
yarn.lock

* Use typescript 4 to be compatible with store

fix: use typescript 4 to be compatible with store

---

package.json
yarn.lock

* fix selectors giving unknown types

chore: update store to fix type errors

---

package.json
yarn.lock

chore: release version 0.3.105

---

package.json
src/components/UiSettings/UiSettings.tsx

feat: add option of subscribe notification for peer metadata update

---

package.json
src/components/ParticipantList/ParticipantInList.tsx
src/components/ParticipantList/ParticipantList.tsx
src/components/ParticipantList/ParticipantProps.ts

feat: add raise hand Icon in Partcipant List

---

package.json
src/components/ParticipantList/ParticipantInList.tsx

fix: update position of Raise Hand Icon in participants list

---

package.json
yarn.lock

chore: update store version for changeName and changeMetadata methods

---

package.json
yarn.lock

build: update version to 0.3.110 for release

---

package.json
yarn.lock

build: bump up version to 0.3.111 for release

---

package.json
yarn.lock

build: update store latest version

---

package.json
yarn.lock

build: update store version

---

package.json
src/components/Preview/Preview.tsx
src/index.ts
src/utils/index.ts
yarn.lock

*
*
With Warning:
Without Warning:

fix: add warning for safari audio output change in preview

---

package.json
yarn.lock

* store changes Include proper handling of multiple audio plugins

build: update store

---

src/components/UiSettings/UiSettings.stories.tsx
src/components/UiSettings/UiSettings.tsx

UISettings.Stories-> Added functionality for active Speaker view
UISettings -> Added functionality for active Speaker view

feat: add option to switch to active speaker mode

---

package.json
src/utils/index.ts

refactor: change isSafari method

---

package.json
yarn.lock

- preview promise resolution fix

build: update sdk

---

package.json
yarn.lock

* Refactor complex methods in sdk
* fix mute all not working

build: update sdk, store

---

package.json
src/components/UiSettings/UiSettings.stories.tsx
src/components/UiSettings/UiSettings.tsx
src/components/UiSettings/UiSettingsSection.tsx

feat: add option for active speaker mode

---

package.json
yarn.lock

build: update store to latest, bump version

---

package.json
yarn.lock

build: update store with hls support(alpha)

---

package.json
yarn.lock

build: update store version for HLS

---

package.json
yarn.lock

build: update store version for new HLS interface

---

package.json
src/components/VideoList/VideoList.tsx
src/utils/videoListUtils.ts

feat: add option to show a tile for each peer in videoList

---

package.json
src/components/Settings/Settings.tsx
yarn.lock

feat: show deviceSettings for hls-viewer

---

package.json
src/hooks/HMSRoomProvider.tsx
src/hooks/storeHook.ts
src/storybook/store/SetUpFakeStore.ts
yarn.lock

fix: webrtc stats

---

package.json
yarn.lock

build: update sdk, bump version for release

---

package.json
src/components/VideoTile/Stats/Stats.tsx
src/components/VideoTile/Stats/index.tsx
src/components/VideoTile/VideoTile.tsx
src/utils/index.ts
yarn.lock

* Enable `showStats` prop on VideoTile to show Stats for Nerds.

feat: Stats on VideoTiles

---

package.json
yarn.lock

build: update store and bump version

---

package.json
yarn.lock

build: update store, bump version for release

---

package.json
src/components/VideoTile/Stats/Stats.tsx
src/components/VideoTile/Stats/stats.css
src/components/VideoTile/VideoTile.tsx

* Replace CSS grid with table
* Abbreviate labels for small tiles
* Max height and scroll for small tiles

fix: stats on small tiles

---

package.json
src/components/VideoTile/Stats/Stats.tsx
yarn.lock

* Resolution as Width*Height instead of Height*Width.
* Don't show resolution when not available on mobile.

fix: stats UI

---

package.json
src/components/Playlist/AudioPlaylist.tsx
src/components/Playlist/VideoPlaylist.tsx

fix: av playlist tooltip

---

.github/workflows/create-store-update-pr.yml

fix: store workflow

---

README.md

fix: fix link in readme

---

package.json
yarn.lock

fix: react-ui version, bump for release

---

package.json
src/components/Playlist/AudioPlaylist.tsx
src/components/Playlist/VideoPlaylist.tsx
yarn.lock

feat: remove react-ui dependency

---

src/components/ParticipantList/ParticipantList.tsx
src/hooks/HMSRoomProvider.tsx

fix: type error in notifications

---

src/components/VideoTile/VideoTile.tsx
src/utils/index.ts
src/utils/videoListUtils.ts

fix: video track type errors

---

src/components/VideoTile/VideoTile.tsx
src/storybook/store/StoryBookSDK.ts

fix: type errors
