package.json, src/components/VideoTile/VideoTile.tsx
- video track id is passed for selecting preferred layer
- pass screenshare video track id when screenshare is enabled
=> fix: screenshare simulcast handling

package.json, src/components/VideoTile/VideoTile.tsx, src/utils/index.ts, yarn.lock
Show avatar and indicate the label that the video tile's track has been degraded
No visual indication of track degradation
Avatar is shown and label would be appended with '(Degraded)'.
=> chore: Bump versions, add avatar, label for degraded

package.json, src/components/ContextMenu/ContextMenu.tsx, src/components/VideoTile/VideoTile.tsx, src/utils/index.ts, yarn.lock
- Simulcast options are hardcoded
- Pick Simulcast options from the track layer definitions
=> fix: show simulcast options conditionally

package.json, src/components/Preview/Controls/PreviewControls.tsx, src/components/Settings/Settings.tsx, src/components/Settings/TestAudio.tsx, yarn.lock
- Even if the role is not allowed to publish audio/video, device selection is shown
- This results in the device dropdown being empty as permissions are not requested for that
- Show relevant device change based on the role
For viewer role, it would be something like this
=> fix: show setttings based on role

package.json, src/components/ParticipantList/ParticipantInList.tsx
- Hide settings icon if the user doesn't have permission to change roles.
=> fix: hide settings icon if no permission

package.json, src/components/ControlBar/ControlBar.tsx
adjust spacing on control bar components
- The left bar relied on fixed width to provide spacing, if the number of components increase or decrease, the spacing becomes inconsistent
- modified the CSS to allow for any number of components keeping the spacing consistent
=> fix: adjust spacing on control bar components

package.json, src/components/ContextMenu/ContextMenu.tsx, src/components/ContextMenu/index.css, src/components/VideoTile/VideoTile.tsx, src/components/VideoTile/index.css, yarn.lock
- Context Menu doesn;t show properly when tile is small
- Context Menu is not cutoff when tile is at the bottom
- Most cases are handled automatically by using material context menu
=> fix: use material context menu

package.json, src/components/Settings/Settings.tsx
- On Device changes, Settings does not show the correct selected device
- Updating settings whenever the store value changes
=> fix: show correct selected devices in settings

package.json, src/components/Button/Button.tsx, src/components/Preview/Preview.tsx
Don't allow clicking disabled preview button to avoid joining when preview is in progress
Clicking disabled button could trigger onClick
Clicking disabled button doesn't do anything
=> fix: Button disabled(for preview)

package.json, src/components/ChatBox/ChatBox.tsx, src/components/ChatBox/ChatSelector.tsx
- Participant selection is getting hidden when chat is scrolled
- Fix the scroll
=> fix: chat selector ui

package.json, src/components/ChatBox/ChatBox.tsx, src/components/ChatBox/ChatSelector.tsx, src/storybook/store/SetUpFakeStore.ts, yarn.lock
- Private messages are shown in everyone.
- Show only broadcast messages for everyone
- Only mark messages read if the relevant view is open
=> fix: broadcast messages, unread count

package.json, src/components/ChatBox/ChatBox.tsx, yarn.lock
- SendMessage is used to broadcast, group and private messages
- Use different methods for different type of messages.
=> refactor: update private message interfaces

package.json, src/components/ContextMenu/ContextMenu.tsx, src/components/VideoTile/VideoTile.tsx, yarn.lock
- Add context menu item for remove peer
- Don't show video remote mute for screenshare
- Remote muting screenshare leads to blank tile
- Don't allow remote muting screenshare video
=> feat: Add menu item for remove peer

package.json, src/components/VideoTile/VideoTile.tsx
- Audio remote mute menu item doesn't show up
- Audio remote mute menu item shows up when there's a store audio track
=> fix: Show screen audio remote mute menu item

package.json, src/components/VideoTile/VideoTile.tsx, yarn.lock
- Bump hms-video@0.0.145, hms-video-store@0.2.18
- Show superpower buttons only when permitted
- Remote mute, remove peer buttons come up for unpermitted roles too.
- Superpower buttons only appear when role is permitted.
=> fix: Superpower buttons only when permitted

package.json, src/components/Preview/Preview.tsx
- https://100ms.atlassian.net/browse/HMS-3670
- https://100ms.atlassian.net/browse/HMS-3147
- In preview video tile size is much smaller in safari
- Make it consistent with other browsers
=> fix: preview video tile size

package.json, src/components/ContextMenu/ContextMenu.tsx, src/components/VideoTile/VideoTile.tsx
- Remove participant alignment is not correct. Goes to next line
- Update remote participant text and color
=> fix: remove peer text alignment

package.json, src/components/ParticipantList/ParticipantInList.tsx, src/components/ParticipantList/ParticipantList.tsx
- Long participant name is creating a scroll in participant list
- Show ellipsis for long participant text
- Handle long text in role change modal
=> fix: long text in participant list

package.json, src/components/ChatBox/ChatBox.tsx, src/components/ParticipantList/ParticipantList.tsx, src/components/VideoTile/VideoTile.tsx, src/hooks/HMSThemeProvider.tsx, src/hooks/interfaces/HMSThemeProvider.ts
- Await and wrap superpower actions in try catch.
- Catch the error and toast the error message.
- Accept toast function from web app as prop in HMSThemeProvider.
- Provide to all components using useHMSTheme hook.
- Superpower errors are uncaught.
- No way to toast from components
- Catch errors from superpower
- Use toast to display them
=> feat: Add toast errors for superpower actions

package.json, src/components/ParticipantList/ParticipantList.tsx, src/components/Settings/Settings.tsx
- ChangeRole modal overflowing width
- Camera label too big in mobile
- Settings are too small on mobile
- Fix ChangeRole modal with
- Remove deviceid from camera name
- Adjust settings UI, make it vertical on mobile
=> fix: mweb UI fixes

package.json, src/components/TwAvatar/Avatar.tsx, src/components/VideoTile/VideoTile.tsx, yarn.lock
- Preview video tile overflows when space available is less
- Hide the excess overflow.
- Fix avatar in participant list
=> fix: preview video overflowing container

package.json, src/components/VideoTile/VideoTile.tsx, yarn.lock
- Audio level indicator not visible because of overflow.
- use min-height:0 instead of overflow to prevent element moving out of container
=> fix: audio level indicator

src/components/Button/Button.tsx, src/components/Preview/Preview.stories.tsx, src/components/Preview/Preview.tsx, src/components/Text/Text.tsx, src/utils/classes/index.tsx
* Allow nested parsing of classes. For example, set class of root in joinButton inside Preview. Example:
```jsx
<Preview
classes={{
joinButton: {
rootEmphasized: 'bg-yellow-500',
},
}}
/>
```
- Make nested classes for VideoList, VideoTile, Video.
=> fix: Nested class parsing

package.json, src/components/ControlBar/ControlBar.tsx, src/components/Dialog/Dialog.tsx, src/components/Dialog/index.tsx, src/components/Header/Header.tsx, src/components/ParticipantList/ParticipantList.tsx, src/components/Settings/Settings.tsx, src/index.ts
:lipstick: :recycle: Exporting the default HMSDialog and converting props to be optional in various places.
* It will expose your HMSDialog component which so that i don't have to use `@material/core` in my repo.
* It will make some components TS compatible as it makes some props optional which have default implementation.
=> feat: export HMSDialog and convert props to be optional

src/components/VideoList/VideoList.tsx, src/components/VideoTile/VideoTile.tsx
* Only show default overlay options on video tile when `showDefaultOverlayOptions`(defaults to true) is true
Tile without default overlay
=> Added `showDefaultOverlayOptions` prop for videoTile
